apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asbdemo

resources:
- namespace.yaml
- gateway.yaml
- ../../orders-service
- ../../payments-service

images:
- name: acrasbdemodevsin.azurecr.io/orders-service
  newName: acrasbdemodevsin.azurecr.io/orders-service
  newTag: 2bf48c9
- name: acrasbdemodevsin.azurecr.io/payments-service
  newName: acrasbdemodevsin.azurecr.io/payments-service
  newTag: 2bf48c9

labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/part-of: asbdemo
    env: dev
