apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  labels:
    app.kubernetes.io/name: orders-service
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 30s
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              sum(rate(http_server_requests_seconds_count{job="{{args.service-name}}",status!~"5.."}[2m]))
              /
              sum(rate(http_server_requests_seconds_count{job="{{args.service-name}}"}[2m]))
            ) or vector(1)
