apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  labels:
    app.kubernetes.io/name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: orders-sa
      terminationGracePeriodSeconds: 40
      containers:
        - name: orders-service
          image: acrasbdemodevsin.azurecr.io/orders-service:bootstrap
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVICEBUS_NAMESPACE_FQDN
              value: "sb-asbdemo-dev-sin-znsc.servicebus.windows.net"
            - name: SERVICEBUS_QUEUE_NAME
              value: "orders"
          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
