apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  annotations:
    azure.workload.identity/client-id: "05dd4406-9204-4162-87a7-c7b1763627ff"
  labels:
    app.kubernetes.io/name: orders-service
    azure.workload.identity/use: "true"
