apiVersion: v1
kind: Service
metadata:
  name: payments-service-preview
  labels:
    app.kubernetes.io/name: payments-service
    role: preview
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payments-service
  ports:
    - name: http
      port: 80
      targetPort: http
