apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payments-service
  labels:
    app.kubernetes.io/name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-service
  strategy:
    blueGreen:
      activeService: payments-service
      previewService: payments-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: payments-sa
      terminationGracePeriodSeconds: 40
      containers:
        - name: payments-service
          image: acrasbdemodevsin.azurecr.io/payments-service:bootstrap
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICEBUS_NAMESPACE_FQDN
              value: "sb-asbdemo-dev-sin-znsc.servicebus.windows.net"
            - name: SERVICEBUS_QUEUE_NAME
              value: "orders"
            - name: OTEL_SERVICE_NAME
              value: "payments-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=dev,service.namespace=asbdemo"
          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]