apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-sa
  annotations:
    azure.workload.identity/client-id: "1c0604b7-9abc-4e31-8a6b-4ce85e26fcfb"
  labels:
    app.kubernetes.io/name: payments-service
    azure.workload.identity/use: "true"
