apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.20.2
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
        global:
          leaderElection:
            namespace: cert-manager
        resources:
          requests: { cpu: "10m", memory: "64Mi" }
          limits:   { cpu: "100m", memory: "128Mi" }
        webhook:
          resources:
            requests: { cpu: "10m", memory: "64Mi" }
            limits:   { cpu: "100m", memory: "128Mi" }
        cainjector:
          resources:
            requests: { cpu: "10m", memory: "64Mi" }
            limits:   { cpu: "100m", memory: "256Mi" }
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true