apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: v1.5.1
    path: config/crd/standard
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicyBinding
      jqPathExpressions:
        - .spec.matchResources.namespaceSelector
        - .spec.matchResources.objectSelector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true