apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-api-crds.yaml
  - cert-manager.yaml
  - argo-rollouts.yaml
  - nginx-gateway-fabric.yaml
  - kube-prometheus-stack.yaml
  - jaeger.yaml
  - eck-operator.yaml
  - elastic-stack.yaml